### ISSUE TITLE
Subgraphs / pattern organization and reusability

### ISSUE THREAD

**Issue by rpearl** [chlorophyll/chlorophyll#59] opened 2017-05-01 18:17 UTC
It will certainly be the case that as patterns grow more complex we'll want to be able to collapse down subgraphs of a pattern into an abstract node with inputs and outputs.

There's some interesting usability concerns here so this is probably further off. The original Litegraph editor has this feature so we can take cues from that.

**Comment by cwill** [comment] 2018-01-08 05:41
Closing this as a more general duplicate of #121

**Closed by cwill** 2018-01-08 05:41 UTC
Labels: feature, improvement, low priority, patterns
